apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: cloudclub
  labels:
    app: cc-deployment-demo
spec:
  selector:
    app: hello-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080
