apiVersion: v1
kind: Pod
metadata:
  name: my-command-pod
  namespace: my-ns
  labels:
    app: my-command-app
spec:
  containers:
  - name: my-command-container
    image: busybox
    command: ['echo', "Welcome to my namespace"]
  restartPolicy: Never
