apiVersion: v1
kind: Pod
metadata:
  name: my-ns-pod
  namespace: my-ns
  labels:
    app: my-apps-1
spec:
  containers:
    - name: my-app-container
      image: busybox
      command: ['sh','-c', 'echo hello k8! && sleep 3600']
