apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-apps-2
spec:
  containers:
    - name: my-app-container
      image: busybox
      command: ['sh','-c', 'echo hello k8! && sleep 3600']
